version: 0.2

env:
  variables:
    GITHUB_REPO_URL: "https://github.com/eaknath-traf/CodeBuild-Pipeline-Integration"
    RUNNER_LABELS: "codebuild"
    RUNNER_HOME: "/actions-runner"
    # token passed via env/parameter store or CodeBuild env var, not hard-coded
    RUNNER_REGISTRATION_TOKEN: "BYQOQFBDUFTY64Z6EYYLYPLJFBKLG"

phases:
  build:
    commands:
      - echo "Waiting for GitHub Actions job to finish..."
      - while pgrep -f run.sh > /dev/null; do
          sleep 5;
        done
