version: 0.2

env:
  variables:
    RUNNER_BINARY_URL: "https://github.com/actions/runner/releases/download/v2.309.0/actions-runner-linux-x64-2.309.0.tar.gz"
    GITHUB_REPO_URL: "https://github.com/eaknath-traf/CodeBuild-Pipeline-Integration"
    RUNNER_LABELS: "codebuild"
    RUNNER_REGISTRATION_TOKEN: "BYQOQFC6XJIH6KT7XBUFRNLJFAVDY"

phases:
  install:
    commands:
    - echo "Installing GitHub Actions Runner..."
    - mkdir -p actions-runner
    - cd actions-runner
    - curl -O -L $RUNNER_BINARY_URL
    - tar xzf ./actions-runner-linux-x64-2.309.0.tar.gz
    - ./bin/installdependencies.sh

  pre_build:
    commands:
      - echo "Configuring GitHub Runner as runneruser..."
      - su - runneruser -c "
          cd ~/actions-runner &&
          ./config.sh --unattended --url $GITHUB_REPO_URL --token $RUNNER_REGISTRATION_TOKEN --labels $RUNNER_LABELS
        "
      - echo "Pre-build complete."

  build:
    commands:
      - echo "Starting GitHub Runner (logs will stream below)..."
      - su - runneruser -c "
          cd ~/actions-runner &&
          ./run.sh
        "

  post_build:
    commands:
      - echo "Post-build phase started..."
      - su - runneruser -c "
          cd ~/actions-runner &&
          ./config.sh remove --unattended --token $RUNNER_REGISTRATION_TOKEN
        "
      - echo "Post-build complete."
